services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: municipal_db
      POSTGRES_USER: municipal_user
      POSTGRES_PASSWORD: municipal_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
